# Generated by Django 4.2.3 on 2023-09-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('candidate', 'Candidate'), ('admin', 'Admin')], max_length=10),
        ),
    ]
