# Generated by Django 4.2.3 on 2023-09-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='SocialMediaPlatforms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_experience',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('candidate', 'Candidate'), ('admin', 'Admin')], default=('admin', 'Admin'), max_length=10),
        ),
    ]
